create table if not exists public.guest_events (
  id bigint generated by default as identity primary key,
  guest_id text not null,
  event_name text not null,
  feature text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists guest_events_created_at_idx
  on public.guest_events (created_at desc);

create index if not exists guest_events_guest_id_idx
  on public.guest_events (guest_id);

create index if not exists guest_events_feature_event_idx
  on public.guest_events (feature, event_name);

alter table public.guest_events enable row level security;

create policy "Allow anonymous guest event inserts"
  on public.guest_events
  for insert
  to anon
  with check (
    guest_id like 'guest_%'
    and event_name in (
      'guest_started',
      'guest_qimen_asked',
      'guest_bazi_viewed',
      'guest_bazi_profile_added',
      'guest_fortune_viewed'
    )
    and feature in ('auth', 'qimen', 'bazi', 'fortune')
  );

